<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InsuranceApp.Domain\InsuranceApp.Domain.csproj" />
    <ProjectReference Include="..\InsuranceApp.Models\InsuranceApp.Models.csproj" />
  </ItemGroup>

</Project>
